# Generated by Django 5.2.1 on 2025-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0014_fix_salesforce_null_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('form_title', models.CharField(help_text='Title of the download form', max_length=255)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('organization', models.CharField(blank=True, help_text='Organization name', max_length=255)),
                ('salesforce_contact_id', models.CharField(blank=True, help_text='Salesforce Contact ID', max_length=50)),
                ('salesforce_account_id', models.CharField(blank=True, help_text='Salesforce Account ID', max_length=50)),
                ('salesforce_task_id', models.CharField(blank=True, help_text='Salesforce Task ID', max_length=50)),
                ('salesforce_sync_error', models.TextField(blank=True, help_text='Error message if Salesforce sync failed')),
                ('salesforce_synced_at', models.DateTimeField(blank=True, help_text='When successfully synced to Salesforce', null=True)),
                ('salesforce_sync_pending', models.BooleanField(default=True, help_text='Whether this needs to be synced to Salesforce')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
